// flow-typed signature: da5bb561f8d1e3a9cfaa40843c945a7b
// flow-typed version: <<STUB>>/coffe-script_v1.11.1/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'coffe-script'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'coffe-script' {
  declare module.exports: any;
}
