// flow-typed signature: 177ec98a0198e86509725c9aaeb4627b
// flow-typed version: <<STUB>>/di_v0.0.1/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'di'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'di' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'di/lib/annotation' {
  declare module.exports: any;
}

declare module 'di/lib/index' {
  declare module.exports: any;
}

declare module 'di/lib/injector' {
  declare module.exports: any;
}

declare module 'di/lib/module' {
  declare module.exports: any;
}

// Filename aliases
declare module 'di/lib/annotation.js' {
  declare module.exports: $Exports<'di/lib/annotation'>;
}
declare module 'di/lib/index.js' {
  declare module.exports: $Exports<'di/lib/index'>;
}
declare module 'di/lib/injector.js' {
  declare module.exports: $Exports<'di/lib/injector'>;
}
declare module 'di/lib/module.js' {
  declare module.exports: $Exports<'di/lib/module'>;
}
