// flow-typed signature: 436adb05ab61aa7941c6fbc1954cdd57
// flow-typed version: <<STUB>>/expand-braces_v0.1.2/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'expand-braces'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'expand-braces' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'expand-braces/index' {
  declare module.exports: $Exports<'expand-braces'>;
}
declare module 'expand-braces/index.js' {
  declare module.exports: $Exports<'expand-braces'>;
}
